environment_path: ./files
use_dangerous_test_keystore: false
signing_service_uri: ~
encryption_service_uri: ~
decryption_service_uri: ~
dpki: ~
keystore_path: ~
passphrase_service: ~
admin_interfaces:
    - driver:
        type: websocket
        port: 22799
network:
  bootstrap_service: "https://bootstrap.holo.host"
  transport_pool:
    - type: proxy
      sub_transport:
        type: quic
      proxy_config:
        type: remote_proxy_client
        proxy_url: "kitsune-proxy://CIW6PxKxsPPlcuvUCbMcKwUpaMSmB7kLD8xyyj4mqcw/kitsune-quic/h/165.22.32.11/p/5778/--"
  tuning_params:
    gossip_loop_iteration_delay_ms: 1000
    default_notify_remote_agent_count: 5
    default_notify_timeout_ms: 1000
    default_rpc_single_timeout_ms: 20000
    default_rpc_multi_remote_agent_count: 2
    default_rpc_multi_timeout_ms: 2000
    agent_info_expires_after_ms: 180000 # 30 minutes
    tls_in_mem_session_storage: 512
    proxy_keepalive_ms: 120000
    proxy_to_expire_ms: 300000
